include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - import_lint

import_lint:
  rules:
    restrict_imports_to_common:
      target: "package:schema_form_builder/**/*.dart"
      from: "package:schema_form_builder/lib/src/**/*.dart"
      except: ["package:schema_form_builder/schema_form_builder.dart"]
